import {
  KEY_SECRET_MONGODB,
  API_HEROKU,
  ETH_MAINNET,
  MARKETCAP_API_KEY,
  PASSWORD_EARLY,
} from '@env';

export default {
  KEY_SECRET_MONGODB,
  API_HEROKU,
  ETH_MAINNET,
  MARKETCAP_API_KEY,
  PASSWORD_EARLY,
};
